name: svt-av1
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt-get install -y gcc-9 g++-9 nasm yasm cmake
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Compile SVT-AV1
      run: |
        export CC=gcc-9 CXX=g++-9
        ./Build/linux/build.sh release
        ./Bin/Release/SvtAv1EncApp -help
